# Generated by Django 5.1.7 on 2026-03-21 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zajecia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('WYK', 'Wykład'), ('LAB', 'Laboratorium'), ('CWI', 'Ćwiczenia'), ('SEM', 'Seminarium'), ('PRO', 'Projekt'), ('INN', 'Inne')], default='WYK', max_length=3)),
                ('dzien_tygodnia', models.IntegerField(choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')])),
                ('godzina_start', models.TimeField()),
                ('czas_trwania_min', models.PositiveIntegerField()),
                ('data_od', models.DateField()),
                ('data_do', models.DateField()),
                ('sala', models.CharField(blank=True, default='', max_length=50)),
                ('prowadzacy', models.CharField(blank=True, default='', max_length=200)),
                ('notatki', models.TextField(blank=True, default='')),
                ('utworzone', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zajecia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zajęcia',
                'verbose_name_plural': 'Zajęcia',
                'ordering': ['dzien_tygodnia', 'godzina_start'],
            },
        ),
    ]
